[project]
name = "prefect-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "griffe==0.49.0",
 "prefect==2.13.7",
 "streamlit>=1.45.1",
]
